PROJECT := test
ARMCC   :=
DEFS    :=
INCS    := include
SRCS    := src/main.c
LIBS    :=
SCRIPT  :=
COMMON  := common

#----------------------------------------------------------#
include $(COMMON)/intros/make/stm32f4discovery/makefile.armcc
#----------------------------------------------------------#

include $(COMMON)/cmsis/makefile
include $(COMMON)/device/makefile
include $(COMMON)/startup/makefile
include $(COMMON)/intros/makefile

#----------------------------------------------------------#
include $(COMMON)/make/makefile
#----------------------------------------------------------#
