name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4' # The arm-none-eabi-gcc release to use.
    - name: check arm-none-eabi-gcc version
      run: arm-none-eabi-gcc -v
    - name: make test
      run: bash ./.test.sh
