name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4' # The arm-none-eabi-gcc release to use.
    - name: check arm-none-eabi-gcc version
      run: arm-none-eabi-gcc -v
    - name: make test
      run: bash ./.test.sh
